// <auto-generated />
namespace PhotoShare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CompleteDbStructure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompleteDbStructure));
        
        string IMigrationMetadata.Id
        {
            get { return "201611011545252_CompleteDbStructure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
